services:
  - type: web
    name: kotobax-web
    env: python
    buildCommand: ""
    startCommand: gunicorn app:app
    disk:
      name: kotobax-disk
      mountPath: /debug

  - type: worker
    name: kotobax-crawler
    env: python
    startCommand: python crawler.py
    disk:
      name: kotobax-disk
      mountPath: /debug
